site_name: TruCtrl Documentation
theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.top
    - navigation.sections
    - navigation.expand
    - navigation.tracking
    - navigation.instant
    - navigation.tabs.sticky